### ISSUE TITLE
agoric start fails with SyntaxError

### ISSUE THREAD

**Issue by dckc** [ski/umqhele#11]
This isn't really an umqhele issue, but it's blocking my work on umqhele / hack-the-orb.

cc @mfig @katelynsills 

```
connolly@jambox:~/projects/umqhele$ agoric start --reset
agoric: start: removing _agstate/agoric-servers/dev
agoric: start: rm -rf _agstate/agoric-servers/dev
agoric: start: initializing dev
agoric: start: /home/connolly/projects/agoric/ag-sdk-orb/packages/cosmic-swingset/bin/ag-solo init dev --egresses=fake --webport=8000
agoric: start: setting sim chain with 0 second delay
agoric: start: /home/connolly/projects/agoric/ag-sdk-orb/packages/cosmic-swingset/bin/ag-solo set-fake-chain --delay=0 sim-chain
agoric: start: /home/connolly/projects/agoric/ag-sdk-orb/packages/cosmic-swingset/bin/ag-solo start
error running ag-solo: (SyntaxError#1)

  SyntaxError#1: Unexpected character '' (1:0)
     at Parser.raise (/home/connolly/projects/agoric/ag-sdk-orb/node_modules/@agoric/babel-parser/lib/parser/location.js:27:17)
    at Parser.getTokenFromCode (/home/connolly/projects/agoric/ag-sdk-orb/node_modules/@agoric/babel-parser/lib/tokenizer/index.js:644:10)
    at Parser.nextToken (/home/connolly/projects/agoric/ag-sdk-orb/node_modules/@agoric/babel-parser/lib/tokenizer/index.js:144:12)
    at Parser.parse (/home/connolly/projects/agoric/ag-sdk-orb/node_modules/@agoric/babel-parser/lib/parser/index.js:38:10)
    at parse (/home/connolly/projects/agoric/ag-sdk-orb/node_modules/@agoric/babel-parser/lib/index.js:44:38)
    at transform (/home/connolly/projects/agoric/ag-sdk-orb/packages/transform-eventual-send/src/index.js:8:38)
    at Object.transform (/home/connolly/projects/agoric/ag-sdk-orb/packages/bundle-source/src/index.js:25:15)
    at Function.apply (/home/connolly/projects/agoric/ag-sdk-orb/packages/tame-metering/src/tame.js:172:20)
    at /home/connolly/projects/agoric/ag-sdk-orb/packages/bundle-source/node_modules/rollup/dist/shared/node-entry.js:13117:25
  
Maybe the chain has bumped and you need to rerun ag-setup-solo?
```

**Comment by katelynsills** [comment]
Hmm, have you tried removing the node_modules from the agoric-sdk side? And making sure you are on the hackathon branch? Let's elevate this to a bug report on agoric-sdk as well.

**Comment by katelynsills** [comment]
@dckc I was thinking of making the issue on agoric-sdk myself, but I realized it would be better if you [could fill in the details](https://github.com/Agoric/agoric-sdk/issues/new?assignees=&labels=bug&template=bug_report.md&title=Syntax%20Error%20when%20running%20`agoric%20start%20--reset`) with your particular setup  Thanks!

**Comment by dckc** [comment]
moved to https://github.com/Agoric/agoric-sdk/issues/2046
