### ISSUE TITLE
possible html comment syntax rejected around line

### ISSUE THREAD

**Issue by ski** [ski/umqhele#14]
CapTP bundle exception: (SyntaxError#1)

  SyntaxError#1: possible html comment syntax rejected around line 10
     at fullRevive (/home/ski/agoric-sdk/packages/marshal/src/marshal.js:738:34)
    at unserialize (/home/ski/agoric-sdk/packages/marshal/src/marshal.js:790:19)
    at CTP_RETURN (/home/ski/agoric-sdk/packages/captp/lib/captp.js:326:16)
    at dispatch (/home/ski/agoric-sdk/packages/captp/lib/captp.js:385:9)
    at WebSocket.<anonymous> (/home/ski/agoric-sdk/packages/agoric-cli/lib/deploy.js:109:13)
    at WebSocket.emit (events.js:314:20)
    at WebSocket.EventEmitter.emit (domain.js:483:12)
    at Receiver.receiverOnMessage (/home/ski/agoric-sdk/node_modules/ws/lib/websocket.js:800:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.EventEmitter.emit (domain.js:483:12)
    at Receiver.dataMessage (/home/ski/agoric-sdk/node_modules/ws/lib/receiver.js:423:14)
    at Receiver.getData (/home/ski/agoric-sdk/node_modules/ws/lib/receiver.js:353:17)
    at Receiver.startLoop (/home/ski/agoric-sdk/node_modules/ws/lib/receiver.js:139:22)
    at Receiver._write (/home/ski/agoric-sdk/node_modules/ws/lib/receiver.js:74:10)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Receiver.Writable.write (_stream_writable.js:318:11)
    at Socket.socketOnData (/home/ski/agoric-sdk/node_modules/ws/lib/websocket.js:875:35)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at addChunk (_stream_readable.js:298:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
  
  SyntaxError#1 ERROR_NOTE: Received as error#1
agoric: (SyntaxError#1)

**Comment by ski** [comment]
Moving to the main branch fixed this one.
